# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
        # Set up JDK for the generator app.
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'microsoft'
            java-package: 'jdk'
  

        # Get the .NET SDK repo
        - name: Checkout dotnet-algorand-sdk repo
          uses: actions/checkout@v3
          
        # Check out the algod oas json
        - name: Download oas2.json file
          run: curl -L https://raw.githubusercontent.com/algorand/go-algorand/master/daemon/algod/api/algod.oas2.json -o dotnet-algorand-sdk/api-generator/dotnet_templates/algod.oas2.json
        
        # Clear 
        - name: Remove the generated transactions
          run: del dotnet-algorand-sdk\dotnet-algorand-sdk\Algod\Model\Transactions\*.Generated.cs
        
        # Verify
        - name: List files
          run: dir dotnet-algorand-sdk\dotnet-algorand-sdk\Algod\Model\Transactions


        # Generate the transactions model 
        - name: Generate transactions model
          run: java -jar dotnet-algorand-sdk\api-generator\generator-1.0.0-jar-with-dependencies.jar template -s dotnet-algorand-sdk\api-generator\dotnet_templates\Transactions.json -t dotnet-algorand-sdk\api-generator\dotnet_templates\ -m dotnet-algorand-sdk\dotnet-algorand-sdk\Algod\Model\Transactions  -p "dotnet-algorand-sdk\api-generator\dotnet_templates\transactions_model_config.properties"

        # Verify
        - name: List files
          run: dir dotnet-algorand-sdk\dotnet-algorand-sdk\Algod\Model\Transactions


        # Verify
        #  name: List files and folders recursively
        #  run: dir -Recurse
